Repository openreview/openreview-web, pull requests merged in 2025-03, with the labels that each got.

#2226 Fix/ Note Editor - show invitation description
  components/NoteEditor.js
Labels: iccv_2025, automl_2025

#2236 Consoles: Show Meta Review recommendation field only if the field exists in the note
  components/webfield/NoteMetaReviewStatus.js
Labels: iccv_2025

#2234 Fix/ AC console tasks - add extraRoleNames config
  components/webfield/AreaChairConsole.js
  unitTests/AreaChairConsole.test.js
Labels: iccv_2025

#2237 Fix/ PC/SAC Console - Add latest reply column in paper status tab
  components/webfield/AreaChairConsole.js
  components/webfield/NoteReviewStatus.js
  components/webfield/ProgramChairConsole.js
  components/webfield/ProgramChairConsole/PaperStatus.js
  components/webfield/SeniorAreaChairConsole.js
  components/webfield/SeniorAreaChairConsole/PaperStatus.js
  styles/pages/group.scss
  unitTests/SeniorAreaChairConsole.test.js
Labels: needs update for next.js
